Models/CargoDetail.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MvcOnlineTicariOtomasyon.Models;

public class CargoDetail
{
    [Key]
    public int CargoDetailId { get; set; }
    public string CargoDetailDescription { get; set; }
    public string CargoDetailTrackingCode { get; set; }
    public string CargoDetailSender { get; set; }
    public string CargoDetailBuyer { get; set; }
    public DateTime Date { get; set; }
}

Controllers/CargoController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Breadcrumb;
using MvcOnlineTicariOtomasyon.Models;
using PagedList;
using QRCoder;

namespace MvcOnlineTicariOtomasyon.Controllers;

//[Authorize]
[BreadCrumb(Manual = false)]
public class CargoController : Controller
{
    private readonly Context _context = new Context();

    [BreadCrumb(Clear = true)]
    public ActionResult CargoList(string search, int page = 1)
    {
        var cargoDetails = from cargoDetail in _context.CargoDetails select cargoDetail;
        if (!string.IsNullOrEmpty(search))
        {
            cargoDetails = cargoDetails.Where(y => y.CargoDetailTrackingCode.Contains(search));
        }

        return View(cargoDetails.ToList().ToPagedList(page, 5));
    }

    [HttpGet]
    public ActionResult CargoAdd()
    {
        List<SelectListItem> employees = (from employee in _context.Employees.ToList()
                                          select new SelectListItem
                                          {
                                              Text = $"{employee.EmployeeFirstName} {employee.EmployeeLastName}",
                                              Value = $"{employee.EmployeeFirstName} {employee.EmployeeLastName}"
                                          }).ToList();
        ViewBag.employees = employees;

        List<SelectListItem> customers = (from customer in _context.Customers.ToList()
                                          select new SelectListItem
                                          {
                                              Text = $"{customer.CustomerFirstName} {customer.CustomerLastName}",
                                              Value = $"{customer.CustomerFirstName} {customer.CustomerLastName}"
                                          }).ToList();
        ViewBag.customers = customers;

        Random random = new Random();
        char[] items = { 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N' };
        int i1, i2, i3;
        i1 = random.Next(0, items.Length);
        i2 = random.Next(0, items.Length);
        i3 = random.Next(0, items.Length);
        int n1, n2, n3;
        n1 = random.Next(100, 1000);
        n2 = random.Next(10, 99);
        n3 = random.Next(10, 99);
        string trackingCode = $"{n1}{items[i1]}{n2}{items[i2]}{n3}{items[i3]}";
        ViewBag.code = trackingCode;

        //using (MemoryStream memoryStream = new MemoryStream())
        //{
        //    QRCodeGenerator generator = new QRCodeGenerator();
        //    QRCodeGenerator.QRCode qrCode = generator.CreateQrCode(trackingCode, QRCodeGenerator.ECCLevel.Q);
        //    using (Bitmap image = qrCode.GetGraphic(10))
        //    {
        //        image.Save(memoryStream, ImageFormat.Png);
        //        ViewBag.qrCode = "data:image/png/;base64," + Convert.ToBase64String(memoryStream.ToArray());
        //    }
        //}

        return View();
    }
    [HttpPost]
    public ActionResult CargoAdd(CargoDetail cargoDetail)
    {
        cargoDetail.Date = DateTime.Now;
        _context.CargoDetails.Add(cargoDetail);
        _context.SaveChanges();
        return RedirectToAction("CargoList");
    }


    public ActionResult CargoDetail(string trackingCode)
    {
        var result = _context.CargoTrackings.Where(x => x.CargoTrackingCargoTracking == trackingCode).ToList();
        ViewBag.value = trackingCode;
        return View(result);
    }
}

Views/Cargo/CargoAdd.cshtml
@{
    ViewBag.Title = "CargoAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form class="form-group" method="post">
    <section class="content">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col text-center">
                    <h2>Yeni Kargo Girişi</h2>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="col-12 mb-3">
                        <label for="formcontrol1" class="form-label">Takip Kodu</label>
                        <input type="text" name="CargoDetailTrackingCode" value="@ViewBag.code" class="form-control" id="formcontrol1" readonly="readonly">
                    </div>
                    <div class="col-12 mb-3">
                        <label for="formcontrol2" class="form-label">Gönderici</label>
                        <select name="CargoDetailSender" class="form-control" id="formcontrol2">
                            @foreach (var employee in (List<SelectListItem>)ViewBag.employees)
                            {
                                <option value="@employee.Value">@employee.Text</option>
                            }
                        </select>
                    </div>
                    <div class="col-12 mb-3">
                        <label for="formcontrol3" class="form-label">Alıcı</label>
                        <select name="CargoDetailBuyer" class="form-control" id="formcontrol3">
                            @foreach (var customer in (List<SelectListItem>)ViewBag.customers)
                            {
                                <option value="@customer.Value">@customer.Text</option>
                            }
                        </select>
                    </div>
                    <div class="col-12 mb-3">
                        <label for="formcontrol4" class="form-label">Açıklama</label>
                        <textarea rows="5" name="CargoDetailDescription" class="form-control" id="formcontrol4"></textarea>
                    </div>
                    <div class="col-12 mb-3 text-right">
                        <button type="submit" class="btn btn-outline-success" id="btnAdd" style="width:100px">Ekle</button>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>

Views/Cargo/CargoDetail.cshtml
@using MvcOnlineTicariOtomasyon.Models
@model List<CargoTracking>

@{
    ViewBag.Title = "CargoDetail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-4 text-left">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active">Takip Numarası : @ViewBag.value</li>
                </ol>
            </div>
            <div class="col-4 text-center">
                <h2>Kargo Detay</h2>
            </div>
            <div class="col-4 text-right">
            </div>
        </div>
        <div class="row">
            <div class="col">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Açıklama</th>
                            <th>Tarih</th>
                            <th>Saat</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">@item.CargoTrackingId</th>
                                <td>@item.CargoTrackingDescription</td>
                                <td>@Convert.ToDateTime(item.Date).ToString("dd/MM/yyyy")</td>
                                <td>@Convert.ToDateTime(item.Date).ToString("t")</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

Views/Cargo/CargoList.cshtml
@using MvcOnlineTicariOtomasyon.Models
@using PagedList.Mvc
@model PagedList.IPagedList<CargoDetail>

@{
    ViewBag.Title = "CargoList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                <div class="row my-auto">
                    <div class="col-4 text-left">
                        <a href="@Url.Action("CargoAdd", "Cargo")" type="button" class="btn btn-info">Yeni Kargo Girişi</a>
                    </div>
                    <div class="col-4 text-center">
                        <h2>Kargo Listesi</h2>
                    </div>
                    <div class="col-4 text-right">
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Gönderici</th>
                                    <th>Alıcı</th>
                                    <th>Takip Kodu</th>
                                    <th>Tarih</th>
                                    <th>Saat</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <th>@item.CargoDetailId</th>
                                        <td>@item.CargoDetailSender</td>
                                        <td>@item.CargoDetailBuyer</td>
                                        <td>@item.CargoDetailTrackingCode</td>
                                        <td>@Convert.ToDateTime(item.Date).ToString("dd/MM/yyyy")</td>
                                        <td>@Convert.ToDateTime(item.Date).ToString("t")</td>
                                        <td><a href="@Url.Action("CargoDetail", "Cargo", new { trackingCode = item.CargoDetailTrackingCode })" class="btn btn-secondary btn-sm">Detaylar</a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0 float-right">
                    @Html.PagedListPager(Model, page => Url.Action("CargoList", new { page }), new PagedListRenderOptions
                    {
                        LiElementClasses = new List<string> { "page-link" }
                    })
                </ul>
            </div>
        </div>
    </div>
</section>