Controllers/StatisticsController.cs
using MvcOnlineTicariOtomasyon.Breadcrumb;
using MvcOnlineTicariOtomasyon.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers;

//[Authorize]
[BreadCrumb(Manual = false)]
public class StatisticsController : Controller
{
    private readonly Context _context = new Context();

    [BreadCrumb(Clear = true)]
    public ActionResult CardStatistics()
    {
        ViewBag.totalCustomer = _context.Customers.Count();

        ViewBag.totalProduct = _context.Products.Count();

        ViewBag.totalEmployee = _context.Employees.Count();

        ViewBag.totalCategory = _context.Categories.Count();

        ViewBag.totalStock = _context.Products.Sum(x => x.Stock);

        ViewBag.totalBrand = (from product in _context.Products select product.ProductBrand).Distinct().Count();

        ViewBag.criticalLevel = _context.Products.Count(x => x.Stock <= 5);

        ViewBag.highestPricedProduct =
            (from product in _context.Products orderby product.SalePrice descending select product.ProductName)
            .FirstOrDefault();

        ViewBag.value1 = _context.Products.GroupBy(x => x.ProductBrand).OrderByDescending(y => y.Count())
            .Select(z => z.Key).FirstOrDefault();

        ViewBag.freezerCount = _context.Products.Count(x => x.ProductName == "Buzdolabı");

        ViewBag.laptopCount = _context.Products.Count(x => x.ProductName == "Laptop");

        ViewBag.lowestPricedProduct = (from product in _context.Products orderby product.SalePrice select product.ProductName)
            .FirstOrDefault();

        ViewBag.bestSellingProduct = _context.Products.Where(p => p.ProductId == _context.SalesMovements
                .GroupBy(x => x.ProductId)
                .OrderByDescending(y => y.Count())
                .Select(z => z.Key).FirstOrDefault())
            .Select(k => k.ProductName).FirstOrDefault();

        ViewBag.totalPrice = _context.SalesMovements.Sum(x => x.TotalPrice);

        DateTime today = DateTime.Today;

        ViewBag.todaySales = _context.SalesMovements.Count(x => x.Date == today);

        ViewBag.todayTotalPrice = _context.SalesMovements.Where(x => x.Date == today).Sum(y => (decimal?)y.TotalPrice);

        return View();
    }

    public ActionResult SimpleStatistics()
    {
        return View();
    }

    public PartialViewResult PartialCategoryTable()
    {
        return PartialView();
    }

    public PartialViewResult PartialCustomerCityTable()
    {
        var result = from customer in _context.Customers
                     group customer by customer.CustomerCity
            into temp
                     select new ClassGroup
                     {
                         City = temp.Key,
                         Number = temp.Count()
                     };
        return PartialView(result.ToList());
    }

    public PartialViewResult PartialDepartmentEmployeeTable()
    {
        var result = from employee in _context.Employees
                     group employee by employee.Department.DepartmentName
            into temp
                     select new ClassGroup2
                     {
                         DepartmentName = temp.Key,
                         Number = temp.Count()
                     };
        return PartialView(result.ToList());
    }

    public PartialViewResult PartialProductBrandTable()
    {
        var result = from product in _context.Products
                     group product by product.ProductBrand
            into temp
                     select new ClassGroup3
                     {
                         Brand = temp.Key,
                         Number = temp.Count()
                     };
        return PartialView(result.ToList());
    }

    public PartialViewResult PartialCustomerTable()
    {
        return PartialView(_context.Customers.Where(x => x.Deleted == false).ToList());
    }

    public PartialViewResult PartialProductTable()
    {
        return PartialView(_context.Products.Where(x => x.Deleted == false).ToList());
    }

    public ActionResult Graphic1()
    {
        return View();
    }

    public ActionResult Graphic2()
    {
        var graphic = new Chart(width: 600, height: 600);
        graphic.AddTitle(text: "Kategori ve Ürün Stok Sayısı");
        graphic.AddLegend(title: "Stok");
        graphic.AddSeries(
            name: "Veriler",
            //chartType: "Column",
            xValue: new[] { "Mobilya", "Ofis Eşyaları", "Bilgisayar", "Küçük Ev Aletleri" },
            yValues: new[] { 85, 66, 98, 75 }
        );
        graphic.Write();

        return File(graphic.ToWebImage().GetBytes(), "image/jpg");
    }

    public ActionResult Graphic3()
    {
        ArrayList xvalue = new ArrayList();
        ArrayList yvalue = new ArrayList();
        var results = _context.Products.ToList();
        results.ToList().ForEach(x => xvalue.Add(x.ProductName));
        results.ToList().ForEach(y => yvalue.Add(y.Stock));

        var graphic = new Chart(width: 1200, height: 800)
            .AddTitle("Stoklar")
            .AddSeries(
                chartType: "Pie",
                name: "Stok",
                xValue: xvalue,
                yValues: yvalue
            );

        return File(graphic.ToWebImage().GetBytes(), "image/jpg");
    }

    public ActionResult Graphic4()
    {
        return View();
    }
    public ActionResult VisualizeProductResult()
    {
        return Json(data: ProductList(), JsonRequestBehavior.AllowGet);
    }
    public List<ClassGroup4> ProductList()
    {
        List<ClassGroup4> list = new List<ClassGroup4>
        {
            new()
            {
                ProductName = "Bilgisayar",
                Stock = 120
            },
            new()
            {
                ProductName = "Beyaz Eşya",
                Stock = 150
            },
            new()
            {
                ProductName = "Mobilya",
                Stock = 70
            },
            new()
            {
                ProductName = "Çamaşır Makinesi",
                Stock = 180
            },
            new()
            {
                ProductName = "Bulaşık Makinesi",
                Stock = 90
            }
        };
        return list;
    }

    public ActionResult Graphic5()
    {
        return View();
    }
    public ActionResult VisualizeProductResult2()
    {
        return Json(data: ProductList2(), JsonRequestBehavior.AllowGet);
    }
    public List<ClassGroup5> ProductList2()
    {
        List<ClassGroup5> list = new List<ClassGroup5>();
        list = _context.Products.Select(product => new ClassGroup5
        {
            ProductName = product.ProductName,
            Stock = product.Stock
        }).ToList();
        return list;
    }
}

Views/Statistics/Graphic1.cshtml
@{
    ViewBag.Title = "Graphics";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Graphic1</h2>

@{
    var graphic = new Chart(width: 500, height: 500);
    graphic.AddTitle(text: "Kategoriler ve Ürün Sayıları");
    graphic.AddLegend(title: "Değerler");

    graphic.AddSeries(
        name: "Veriler",
        chartType:"Pie",
        xValue: new[] { "Beyaz Eşya", "Televizyon", "Bilgisayar", "Küçük Ev Aletleri" },
        yValues: new[] { 500, 250, 340, 620 }
        );

    graphic.Write();
}

Views/Statistics/Graphic2.cshtml
@{
    ViewBag.Title = "Graphics1";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Graphic2</h2>

<div style="width:600px; height:600px">
    <img src="@Url.Action("Graphic2","Statistics")" />
</div>

Views/Statistics/Graphic3.cshtml
@{
    ViewBag.Title = "Graphic3";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Graphic3</h2>

<div style="width:600px; height:600px">
    <img src="@Url.Action("Graphic3","Statistics")" />
</div>

Views/Statistics/Graphic4.cshtml
@{
    ViewBag.Title = "Graphic4";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<html lang="tr">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Google Chart in ASP.NET Core MVC 5</title>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: 'GET',
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Statistics")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });

            function drawChart(result) {

                var data = new google.visualization.DataTable();
                data.addColumn('string', 'Name');
                data.addColumn('number', 'Quantity');
                var dataArray = [];
                $.each(result, function (i, obj) {
                    dataArray.push([obj.ProductName, obj.Stock]);
                });

                data.addRows(dataArray);

                var piechart_options = {
                    title: 'Ürün Stok Grafiği',
                    width: 400,
                    height: 300
                };
                var piechart = new google.visualization.PieChart(document
                    .getElementById('piechart_div'));
                piechart.draw(data, piechart_options);

                //var barchart_options = {
                //    title: 'Barchart: How Much Products Sold By Last Night',
                //    width: 400,
                //    height: 300,
                //    legend: 'none'
                //};
                //var barchart = new google.visualization.BarChart(document
                //    .getElementById('barchart_div'));
                //barchart.draw(data, barchart_options);
            }
        });
    </script>
</head>
<body>
    <h3>Ürün Stok Tablosu</h3>
    <div id="piechart_div" style="border: 1px solid #ccc"></div>
    @*<div id="barchart_div" style="border: 1px solid #ccc"></div>*@
</body>
</html>

Views/Statistics/Graphic5.cshtml
@{
    ViewBag.Title = "Graphic5";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<html lang="tr">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Google Chart in ASP.NET Core MVC 5</title>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: 'POST',
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult2", "Statistics")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });

            function drawChart(result) {

                var data = new google.visualization.DataTable();
                data.addColumn('string', 'Name');
                data.addColumn('number', 'Quantity');
                var dataArray = [];
                $.each(result, function (i, obj) {
                    dataArray.push([obj.ProductName, obj.Stock]);
                });

                data.addRows(dataArray);

                var piechart_options = {
                    title: 'Ürün - Stok Grafiği',
                    width: 900,
                    height: 600,
                    is3D: true,
                };
                var piechart = new google.visualization.PieChart(document
                    .getElementById('piechart_div'));
                piechart.draw(data, piechart_options);
            }
        });
    </script>
</head>
<body>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col" style="text-align: -webkit-center;">
                    <div id="piechart_div" style="width: 900px; height: 600px;"></div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

Views/Statistics/PartialCategoryTable.cshtml
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Kategori Tablosu</h3>
    </div>
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th style="width: 10px">#</th>
                <th>Kategori Adı</th>
                <th>Progress</th>
                <th style="width: 40px">Oran</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>1.</td>
                <td>Update software</td>
                <td>
                    <div class="progress progress-xs">
                        <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                    </div>
                </td>
                <td><span class="badge bg-danger">55%</span></td>
            </tr>
            <tr>
                <td>2.</td>
                <td>Clean database</td>
                <td>
                    <div class="progress progress-xs">
                        <div class="progress-bar bg-warning" style="width: 70%"></div>
                    </div>
                </td>
                <td><span class="badge bg-warning">70%</span></td>
            </tr>
            <tr>
                <td>3.</td>
                <td>Cron job running</td>
                <td>
                    <div class="progress progress-xs progress-striped active">
                        <div class="progress-bar bg-primary" style="width: 30%"></div>
                    </div>
                </td>
                <td><span class="badge bg-primary">30%</span></td>
            </tr>
            <tr>
                <td>4.</td>
                <td>Fix and squish bugs</td>
                <td>
                    <div class="progress progress-xs progress-striped active">
                        <div class="progress-bar bg-success" style="width: 90%"></div>
                    </div>
                </td>
                <td><span class="badge bg-success">90%</span></td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="card-footer clearfix">
        <ul class="pagination pagination-sm m-0 float-right">
            <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
        </ul>
    </div>
</div>

Views/Statistics/PartialCustomerCityTable.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyon.Models.ClassGroup>

<div class="card card-success">
    <div class="card-header">
        <h3 class="card-title">Müşteri Şehir Tablosu</h3>
    </div>
    <div class="card-body p-0">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Şehir</th>
                    <th>Progress</th>
                    <th style="width: 40px">Adet</th>
                </tr>
            </thead>
            <tbody>
                @{ int rowNumber = 0;}
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@{rowNumber++;} @rowNumber</td>
                        <td>@item.City</td>
                        <td>
                            @{
                                if (item.Number == 1)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-danger" style="width: 25%"></div>
                                    </div>
                                }
                                else if (item.Number == 2)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-warning" style="width: 50%"></div>
                                    </div>
                                }
                                else if (item.Number == 3)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-primary" style="width: 75%"></div>
                                    </div>
                                }
                                else if (item.Number >= 4)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-success" style="width: 100%"></div>
                                    </div>
                                }
                            }
                        </td>
                        <td>
                            @{
                                if (item.Number == 1)
                                {
                                    <span class="badge bg-danger">@item.Number</span>
                                }
                                else if (item.Number == 2)
                                {
                                    <span class="badge bg-warning">@item.Number</span>
                                }
                                else if (item.Number == 3)
                                {
                                    <span class="badge bg-primary">@item.Number</span>
                                }
                                else if (item.Number >= 4)
                                {
                                    <span class="badge bg-success">@item.Number</span>
                                }
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Statistics/PartialCustomerTable.cshtml
@using MvcOnlineTicariOtomasyon.Models
@model List<Customer>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Müşteri Tablosu</h3>

        <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                <div class="input-group-append">
                    <button type="submit" class="btn btn-default">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body table-responsive p-0">
        <table class="table table-hover text-nowrap">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Adı Soyadı</th>
                    <th>Şehir</th>
                    <th>Mail</th>
                </tr>
            </thead>
            <tbody>
            @{ int rowNumber = 0;}
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@{rowNumber++;} @rowNumber</td>
                        <td>@item.CustomerFirstName @item.CustomerLastName</td>
                        <td>@item.CustomerCity</td>
                        <td>@item.CustomerMail</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Statistics/PartialDepartmentEmployeeTable.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyon.Models.ClassGroup2>

<div class="card card-danger">
    <div class="card-header">
        <h3 class="card-title">Departman Personel Tablosu</h3>

        @*<div class="card-tools">
            <ul class="pagination pagination-sm float-right">
                <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
            </ul>
        </div>*@
    </div>
    <div class="card-body p-0">
        <table class="table">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Departman</th>
                    <th>Progress</th>
                    <th style="width: 40px">Adet</th>
                </tr>
            </thead>
            <tbody>
                @{ int rowNumber = 0;}
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@{rowNumber++;} @rowNumber</td>
                        <td>@item.DepartmentName</td>
                        <td>
                            @{
                                if (item.Number == 1)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-danger" style="width: 25%"></div>
                                    </div>
                                }
                                else if (item.Number == 2)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-warning" style="width: 50%"></div>
                                    </div>
                                }
                                else if (item.Number == 3)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-primary" style="width: 75%"></div>
                                    </div>
                                }
                                else if (item.Number >= 4)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-success" style="width: 100%"></div>
                                    </div>
                                }
                            }
                        </td>
                        <td>
                            @{
                                if (item.Number == 1)
                                {
                                    <span class="badge bg-danger">@item.Number</span>
                                }
                                else if (item.Number == 2)
                                {
                                    <span class="badge bg-warning">@item.Number</span>
                                }
                                else if (item.Number == 3)
                                {
                                    <span class="badge bg-primary">@item.Number</span>
                                }
                                else if (item.Number >= 4)
                                {
                                    <span class="badge bg-success">@item.Number</span>
                                }
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Statistics/PartialProductBrandTable.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyon.Models.ClassGroup3>

<div class="card card-warning">
    <div class="card-header">
        <h3 class="card-title">Ürün Marka Tablosu</h3>
    </div>
    <div class="card-body p-0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Marka</th>
                    <th>Progress</th>
                    <th style="width: 40px">Adet</th>
                </tr>
            </thead>
            <tbody>
                @{ int rowNumber = 0;}
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@{rowNumber++;} @rowNumber</td>
                        <td>@item.Brand</td>
                        <td>
                            @{
                                if (item.Number == 1)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-danger" style="width: 25%"></div>
                                    </div>
                                }
                                else if (item.Number == 2)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-warning" style="width: 50%"></div>
                                    </div>
                                }
                                else if (item.Number == 3)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-primary" style="width: 75%"></div>
                                    </div>
                                }
                                else if (item.Number >= 4)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-success" style="width: 100%"></div>
                                    </div>
                                }
                            }
                        </td>
                        <td>
                            @{
                                if (item.Number == 1)
                                {
                                    <span class="badge bg-danger">@item.Number</span>
                                }
                                else if (item.Number == 2)
                                {
                                    <span class="badge bg-warning">@item.Number</span>
                                }
                                else if (item.Number == 3)
                                {
                                    <span class="badge bg-primary">@item.Number</span>
                                }
                                else if (item.Number >= 4)
                                {
                                    <span class="badge bg-success">@item.Number</span>
                                }
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Statistics/PartialProductTable.cshtml
@using MvcOnlineTicariOtomasyon.Models
@model List<Product>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Ürün Tablosu</h3>

        <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                <div class="input-group-append">
                    <button type="submit" class="btn btn-default">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body table-responsive p-0" style="height: 300px;">
        <table class="table table-head-fixed text-nowrap">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Ürün Adı</th>
                    <th>Kategori Adı</th>
                    <th>Markası</th>
                    <th>Stok</th>
                    <th>Alış Fiyatı</th>
                    <th>Satış Fiyatı</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.ProductId</th>
                        <td>@item.ProductName</td>
                        <td>@item.Category.CategoryName</td>
                        <td>@item.ProductBrand</td>
                        <td>@item.Stock</td>
                        <td>@item.PurchasePrice ₺</td>
                        <td>@item.SalePrice ₺</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>